
name: 'dbt_labs_experimental_features_integration_tests'
version: '0.1.0'

profile: 'integration_tests'

source-paths: ["models"]
analysis-paths: ["analysis"] 
test-paths: ["tests"]
data-paths: ["data"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_modules"

quoting:
  identifier: false
  schema: false
    
seeds:
  quote_columns: false
